services:
  mongo:
    image: mongo:4.2
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    command: ["--bind_ip", "0.0.0.0"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: on-failure
    depends_on:
      - mongo
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - DATABASE=mongodb://mongo:27017/fashioncloud

